"""empty message

Revision ID: 7d6dba35e08e
Revises: 0b90bce3e437
Create Date: 2026-09-24 23:56:47.550044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7d6dba35e08e'
down_revision: Union[str, Sequence[str], None] = '0b90bce3e437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backfillticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'queued'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backfillticket', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
